remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
title_from_headings:
  enabled: false

title: "Codebreaker"
description: "An Android implementation of Bulls & Cows (aka Mastermind)"
author:
  name: Nicholas Bennett
  email: nick@nickbenn.com
  copyright: false
